---
- name: this playbook for applying conditions
  hosts: localhost
  become: yes
  tasks:
  - name: install  in nginx Debian based OS Family
    apt:
      name: nginx
      state: latest
    when: ansible_facts['os_family'] == "Debian"
  - name: Install packages in Debian based OS Family
    become: yes
    package:
      name:
        - wget
        - vim
        - unzip
        - net-tools
        - curl
        - tar
      state: latest
      update_cache: yes
    when: ansible_facts['os_family'] == "Debian"
  - name: Install EPEL release for nginx in RedHat based OS Family but CentOs
    yum:
      name: epel-release
      state: present
    when: ansible_facts['os_family'] == "RedHat" and ansible_facts['distribution'] == "CentOS"
  - name: Install nginx web server in RedHat based OS Family but CentOs
    yum:
      name: nginx
      state: latest
      update_cache: true
    when: ansible_facts['os_family'] == "RedHat" and ansible_facts['distribution'] == "CentOS"
