---
- name: this playbook is install tools in remote servers
  hosts: dev
  become: true
  vars:
  - package_one: tree
  - package_two: zip
  - package_three: wget
  - state_one: present
  - state_two: present
  - state_three: present
  tasks:
  - name: tool one
    apt:
      name: '{{ package_one }}'
      state: '{{ state_one }}'
  - name: tool two
    apt:
     name: "{{ package_two }}"
     state: "{{ state_two }}"
  - name: tool three
    apt:
      name: "{{ package_three }}"
      state: "{{ state_three }}"
      update_cache: yes

